import { Inter } from "next/font/google";
import Head from "next/head";
import SearchInput from "../searchInput";
import router from "next/router";

const inter = Inter({ subsets: ["latin"] });

const Layout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  //fake logo to return to home. Using h1 for now
  const handleOnFakeLogoClick = () => {
    router.push("/");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={`${inter.className} w-full pt-24 bg-custom-rose`}>
        <div className="flex gap-x-3 max-w-6xl mx-auto">
          <h1
            className="text-6xl cursor-pointer font-bold text-custom-wenge"
            onClick={handleOnFakeLogoClick}
          >
            GIF
          </h1>
          <SearchInput />
        </div>
      </header>
      <main
        className={`${inter.className} flex min-h-screen flex-col py-12 px-24 bg-custom-rose`}
      >
        {children}
      </main>
    </>
  );
};

export default Layout;
